# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YFcAIXNnWOGonaQbFq7kf6ONq2CghTNe
"""

!apt-get install -y tesseract-ocr
!pip install pytesseract opencv-python-headless

from google.colab import files
uploaded = files.upload()  # pick an image with visible text
image_path = list(uploaded.keys())[0]

import cv2
import pytesseract
import matplotlib.pyplot as plt
import numpy as np

# 1. LOAD IMAGE
image = cv2.imread(image_path)
original = image.copy()

# 2. PREPROCESSING
# Grayscale
gray = cv2.cvtColor(image, cv2.COLOR_BGR2GRAY)

# Gaussian blur — reduces noise before thresholding
blurred = cv2.GaussianBlur(gray, (5, 5), 0)


# kernel_sharpening = np.array([[-1,-1,-1],
#                               [-1, 9,-1],
#                               [-1,-1,-1]])
# sharpened = cv2.filter2D(blurred, -1, kernel_sharpening)

# Adaptive thresholding — handles uneven lighting better than a fixed threshold
thresh = cv2.adaptiveThreshold(
    blurred, 255, # Reverted to using 'blurred' image after removing sharpening
    cv2.ADAPTIVE_THRESH_GAUSSIAN_C,
    cv2.THRESH_BINARY,
    13, 2
)

# Dilation — to thicken text and connect broken characters
kernel = cv2.getStructuringElement(cv2.MORPH_RECT, (2, 2))
thresh = cv2.dilate(thresh, kernel, iterations=1)

# 3. OCR RECOGNITION
custom_config = r'--oem 3 --psm 3' # Changed PSM to 3 for automatic page segmentation
recognized_text = pytesseract.image_to_string(thresh, config=custom_config)

# 4. CONFIDENCE FILTERING (minimum 80%)
data = pytesseract.image_to_data(thresh, config=custom_config, output_type=pytesseract.Output.DICT)

boxes_drawn = original.copy()
high_confidence_words = []

for i in range(len(data['text'])):
    conf = int(data['conf'][i])
    text = data['text'][i].strip()

    if conf >= 80 and text != "":
        high_confidence_words.append((text, conf))
        x, y, w, h = data['left'][i], data['top'][i], data['width'][i], data['height'][i]
        cv2.rectangle(boxes_drawn, (x, y), (x + w, y + h), (0, 255, 0), 2)
        cv2.putText(boxes_drawn, text, (x, y - 5),
                    cv2.FONT_HERSHEY_SIMPLEX, 0.5, (0, 255, 0), 1)

# 5. DISPLAY RESULTS
print("=== RECOGNIZED TEXT (full) ===")
print(recognized_text)

print("\n=== HIGH-CONFIDENCE WORDS (≥80%) ===")
for word, conf in high_confidence_words:
    print(f"'{word}' — {conf}% confidence")

# Show preprocessing stages + final result
fig, axs = plt.subplots(1, 4, figsize=(20, 5))
axs[0].imshow(cv2.cvtColor(original, cv2.COLOR_BGR2RGB))
axs[0].set_title("Original")
axs[1].imshow(gray, cmap='gray')
axs[1].set_title("Grayscale")
axs[2].imshow(thresh, cmap='gray')
axs[2].set_title("Adaptive Threshold")
axs[3].imshow(cv2.cvtColor(boxes_drawn, cv2.COLOR_BGR2RGB))
axs[3].set_title("Detected Text (≥80%)")

for ax in axs:
    ax.axis('off')

plt.tight_layout()
plt.show()
# Overall confidence score for the full output (average of high-confidence words)
if high_confidence_words:
    avg_confidence = sum(conf for _, conf in high_confidence_words) / len(high_confidence_words)
    print(f"\nOverall Output Confidence: {avg_confidence:.1f}%")
else:
    print("\nNo text met the 80% confidence threshold.")